version: '3'

services:
  couchdb:
    # Assign a unique name to the container
    container_name: scan-couch-db
    # Use the specified Docker image for the service
    image: scan-couch-db
    build:
      # Use the current diretory as the build context
      context: .
      # Specify the Dockerfile used for building the image
      dockerfile: Dockerfile
    # Ensure the container restarts automatically if it stops
    restart: always
    # Set the environement variables inside the container
    env_file:
      - .env
    ports:
      # DOCKER_PORT is an optional host port, defaulting to 4200
      # COUCHDB_PORT is the container's port being exposed
      - ${DOCKER_PORT}:${COUCHDB_PORT}
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
